### ISSUE TITLE
tokusei_array

### ISSUE THREAD

**Issue by TUMTUMTARAM** [pkZukan/PokeDocs#3]
Can you get tokusei_array.fbs from Scarlet?

**Comment by kwsch** [comment]
What is the path of the bin file the fbs would be used against? I'm not aware of any ability-config file.

Historically, ability effects have been hardcoded into the game logic, and not stored as a separate paramater/table.

**Comment by SciresM** [comment]
@kwsch He wants an fbs for `avalon/data/tokusei_array.bin`.

But the game does not contain a BFBS for this file.

**Comment by kwsch** [comment]
You can use pkNX's Master Dump to export the above mentioned bin, and the table can be easily reverse engineered using [FlatCrawler](https://github.com/kwsch/FlatCrawler).
![pkNX](https://user-images.githubusercontent.com/6393368/208006936-de822899-b4c6-4918-b17a-d244007aa70d.png)
![FlatCrawler](https://user-images.githubusercontent.com/6393368/208006673-007b4402-b082-4a69-b859-87771f2c91fb.png)

```fbs
table tokusei_array{
    entries:[tokusei];
}

table tokusei{
  tokusei_num: uint16;
  flag1: bool;
  flag2: bool;
  flag3: bool;
  flag4: bool;
  flag5: bool;
  flag6: bool;
  flag7: bool;
  flag8: bool;
}

root_type tokusei_array;
```
